### ISSUE TITLE
Add macOS into release

### ISSUE THREAD

**Issue by decanus** [stasel/WebRTC#11]
Hey, can you bundle the macOS version with the release too?

**Comment by stasel** [comment]
Hey, I've added macOS framework to the build script. It will be available in the next release next week.
Please note that it will not support macOS catalyst projects.

**Comment by gonzag** [comment]
Hi @stasel, do you know what changes are needed for catalyst support?

**Comment by stasel** [comment]
Hey @gonzag 
Catalyst builds are failing due to compilation errors.

Catalyst support requires some changes to the WebRTC source code and/or the build configuration files inside the repository. It's not a trivial change. Someone managed to do that with partial success (audio only) in the following thread: https://groups.google.com/g/discuss-webrtc/c/VZXS4V4mSY4

Unfortunately I don't have the capacity to find a solution myself. You can dig in and try to compile it if you can

**Comment by gonzag** [comment]
Yes, after leaving the comment I've tried to compile it.
I've managed to compile most of it but it fails to build the libvpx library.
Checking the libvpx repo I've learned the build generated will not be optimized:
https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/third_party/libvpx/BUILD.gn#374

In my opinion, there's no motivation yet to have a build for Catalyst because it would perform worst compared to the mac build

**Comment by stasel** [comment]
I agree.
On another note, I have added macOS binaries to the latest release - M91
@decanus can you confirm that it's working as expected?

**Comment by stasel** [comment]
Added macOS support to Package.swift and podspec. macOS is not supported.
Closing the issue. Feel free to reopen the issue if you still experiencing any problems.
